/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-container": "#b5d4f2",
        "surface-tint": "#43617c",
        secondary: "#48607d",
        "on-tertiary": "#ffffff",
        "primary-container": "#3e5c76",
        tertiary: "#593c13",
        surface: "#f8f9fa",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#001d36",
        "tertiary-fixed": "#ffddb6",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "surface-container-low": "#f3f4f5",
        "surface-variant": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#abcae8",
        "on-surface": "#191c1d",
        background: "#f8f9fa",
        "surface-container": "#edeeef",
        "error-container": "#ffdad6",
        primary: "#26445d",
        "inverse-primary": "#abcae8",
        "on-tertiary-fixed": "#2a1800",
        "outline-variant": "#c3c7cd",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d1e4ff",
        "on-surface-variant": "#42474d",
        "tertiary-container": "#735328",
        "on-primary-fixed-variant": "#2b4963",
        "on-tertiary-fixed-variant": "#5e4118",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#eabf8a",
        "on-secondary-fixed-variant": "#304864",
        "secondary-container": "#c3dcfe",
        "secondary-fixed-dim": "#b0c8ea",
        "on-secondary-container": "#49617e",
        "on-tertiary-container": "#f5c993",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#001d31",
        "primary-fixed": "#cce5ff",
        outline: "#73777d",
        "surface-container-highest": "#e1e3e4",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "48px",
        "margin-tablet": "40px",
        unit: "8px",
        "container-max-width": "1200px",
        "gutter-grid": "24px",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
